### ISSUE TITLE
Not a Drexel Student. 

### ISSUE THREAD

**Issue by hungryducks** [jackyliang/Drexel-Shaft-Protection#2]
I'm very intrigued by this script you wrote, looks amazing! New to coding here, thought I'd check github to see if anything like your script existed; and I'm pleased it does. I would love to use this at my school -- University of Oregon-- and I was wondering if this script would still work? U of O uses Bannerweb just like Drexel. Is there particular information I would have to change to make this script work at my school? Or could I just follow your steps and plug in my passwords and CRNs and have it work just fine? Apologies if I'm not understanding how this works entirely, but any help would be appreciated. 

Cheers
HungryDuck

**Comment by jackyliang** [comment]
Hi @hungryducks. While your school uses Bannerweb as well, I really doubt it will work as-is. I wouldn't even try it. This script emulates a "real browser" clicking the specific links which are guaranteed to be either different or in different locations than what Drexel has them. Feel free to read my code to reverse-engineer it, and try checking out the Python Mechanize library to make your own. 

Good luck!

**Comment by hungryducks** [comment]
Hey thanks for the help!
