### ISSUE TITLE
Will this be updated for the new bannerweb?

### ISSUE THREAD

**Issue by derekyerger** [jackyliang/Drexel-Shaft-Protection#8]
Looks like Drexel replaced the registration part of their site. The old version still exists and can be found under "student services" but its unclear whether it works or not.

Thank you!

**Comment by jackyliang** [comment]
Have you tried it that verifies it doesn't work? I think the PR submitted [here](https://github.com/jackyliang/Drexel-Shaft-Protection/pull/7) should fix it. If not, feel free up shoot a PR that does fix it and I'll merge it.

**Comment by BillCai06** [comment]
I can verifies, it still works

**Comment by jackyliang** [comment]
Thanks for verifying @BillCai06! I'm still amazed that people still use this.
